# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aspirants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aspirants',
            new_name='Aspirant',
        ),
    ]
