# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181025_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='diser_name',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='kurator',
            field=models.TextField(default=1),
        ),
    ]
