# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181025_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kurator', models.TextField(default=1)),
                ('diser_name', models.TextField(default=1)),
                ('text', models.TextField()),
                ('hierarchy', models.IntegerField(default=1)),
            ],
        ),
    ]
