# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_aspirant_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='tests',
            field=models.ManyToManyField(related_name='aspirants', to='blog.Test'),
        ),
    ]
