# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181029_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
