# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181029_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='tests',
            field=models.ManyToManyField(related_name='aspirants', to='blog.Test'),
        ),
    ]
