# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181029_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirant',
            name='tests',
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='diser_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='hierarchy',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='intrestings',
            field=models.ManyToManyField(blank=True, null=True, related_name='aspirants', to='blog.Intresting'),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='kurator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='intresting',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intresting',
            name='diser_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intresting',
            name='hierarchy',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='intresting',
            name='kurator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intresting',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intresting',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='hierarchy',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='diser_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='hierarchy',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='kurator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
